"""Stable public facade for deterministic program and function scopes."""

from ._scope_contracts import (
    IO_CHUNK_BYTES,
    U64_LIMIT,
    AddressCoordinate,
    AddressSpaceEvidence,
    CommittedMemoryRun,
    EvidenceOrigin,
    FrozenMemoryBlockDescriptor,
    FunctionScopeEvidence,
    InstructionFlowEvidence,
    PositionedChunk,
    TranslationNamespace,
    ValidatedFunctionObservation,
    ValidatedInstruction,
    ValidatedOperation,
    ValidatedVarnode,
    VarnodeKindCode,
    VerifiedProgramSnapshotEvidence,
)
from ._scope_wire import (
    _coordinate,
    _derive_function_scope,
    _derive_program_scope,
    _function_scope_preimage,
    _program_scope_preimage,
)
from ._scope_detached import load_detached_program_scope
from ._scope_envelope import (
    ConfiguredExtractionEnvelope,
    FrozenProgramViewProvider,
    open_configured_extraction,
)
from ._scope_raw import RawMember, RawObject, parse_raw_json
from ._scope_results import (
    ConstructedFunctionScope,
    ConstructedProgramScope,
    FunctionScopeConstructionResult,
    ProgramScopeConstructionResult,
    ScopeBundleResult,
    ScopeConstructionReason,
    ScopeConstructionStage,
    ScopedFunctionUnit,
    UnresolvedFunctionScope,
    UnresolvedProgramScope,
)

__all__ = [
    "IO_CHUNK_BYTES",
    "U64_LIMIT",
    "AddressCoordinate",
    "AddressSpaceEvidence",
    "CommittedMemoryRun",
    "EvidenceOrigin",
    "FrozenMemoryBlockDescriptor",
    "FunctionScopeEvidence",
    "InstructionFlowEvidence",
    "PositionedChunk",
    "TranslationNamespace",
    "ValidatedFunctionObservation",
    "ValidatedInstruction",
    "ValidatedOperation",
    "ValidatedVarnode",
    "VarnodeKindCode",
    "VerifiedProgramSnapshotEvidence",
    "ConfiguredExtractionEnvelope",
    "ConstructedFunctionScope",
    "ConstructedProgramScope",
    "FrozenProgramViewProvider",
    "FunctionScopeConstructionResult",
    "ProgramScopeConstructionResult",
    "RawMember",
    "RawObject",
    "ScopeBundleResult",
    "ScopeConstructionReason",
    "ScopeConstructionStage",
    "ScopedFunctionUnit",
    "UnresolvedFunctionScope",
    "UnresolvedProgramScope",
    "load_detached_program_scope",
    "open_configured_extraction",
    "parse_raw_json",
]
